[tool.ruff]
line-length = 120
extend-ignore = ["E501", "I001", "F401", "F841", "E402"]

[tool.ruff.lint.per-file-ignores]
"test*.py" = ["ALL"]
"sem2.py" = ["E501"]
"sem3.py" = ["ALL"]
"sem4.py" = ["ALL"]

